version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"

  memes_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  media_api:
    build:
      context: .
      dockerfile: Dockerfile.media
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
